# Generated by Django 3.0.7 on 2020-10-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaProductos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='url_clean',
            field=models.CharField(max_length=255, verbose_name='URL'),
        ),
    ]
