# Generated by Django 3.0.7 on 2021-05-23 15:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('fechaActualizacion', models.DateTimeField(default=datetime.datetime.now)),
                ('actualizadoPor', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('velocidad', models.FloatField()),
                ('fechaActualizacion', models.DateTimeField(default=datetime.datetime.now)),
                ('actualizadoPor', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('velocidad', models.FloatField()),
                ('generacion', models.IntegerField(default=0)),
                ('fechaActualizacion', models.DateTimeField(default=datetime.datetime.now)),
                ('actualizadoPor', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='MarcaProcesador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fechaActualizacion', models.DateTimeField(default=datetime.datetime.now)),
                ('actualizadoPor', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=250)),
                ('velocidad', models.FloatField()),
                ('fechaActualizacion', models.DateTimeField(default=datetime.datetime.now)),
                ('actualizadoPor', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('retroiluminado', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=250)),
                ('material', models.CharField(max_length=250)),
                ('lectorDeHuella', models.BooleanField(default=False)),
                ('duracionBateria', models.IntegerField(default=0)),
                ('fechaActualizacion', models.DateTimeField(default=datetime.datetime.now)),
                ('actualizadoPor', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('disco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Disco')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Marca')),
                ('procesador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Procesador')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Ram')),
            ],
        ),
    ]
